### ISSUE TITLE
[Incomplete deps] error when trying to build

### ISSUE THREAD

**Issue by avrahamcool** [tjmoses/crud-compare#6]
simply cloning the repo, and installing dependencies using npm is not sufficient.

![image](https://user-images.githubusercontent.com/5445320/102466785-2828e300-4058-11eb-8ef4-c71db4ef3cac.png)

**Comment by tjmoses** [comment]
Use the start lifecycle script. Typescript does the building. microbundle is no longer used.

**Comment by avrahamcool** [comment]
Ok.

fixed the PR - to remove the misleading script instead.

**Comment by tjmoses** [comment]
I actually wiped this earlier already.

https://github.com/tjmoses/crud-compare/commit/9792a747eae20ec4f8662181a271ff476d1a25d6
